import {
  BiGhost,
  BiPlanet,
  BiMoon,
  BiBot,
  BiCookie,
  BiMeteor,
  BiRocket,
  BiChip,
  BiAtom,
} from "react-icons/bi"
import { Job } from "../../interfaces/Job"

export const jobQueue: Array<Job> = [
  {
    id: 1,
    icon: <BiGhost size={32} />,
    title: "Software Developer",
    company: "Phantom Tech",
    location: "San Francisco, CA",
    benefits: "$95K/yr - $130K/yr · Medical · 401k · Remote Flexibility",
    tag: "This is an ad",
  },
  {
    id: 2,
    icon: <BiPlanet size={32} />,
    title: "Software Engineer II",
    company: "Orbit Solutions",
    location: "Remote",
    benefits: "$105K/yr - $145K/yr · 401k, Medical, Vision, Dental",
  },
  {
    id: 3,
    icon: <BiMoon size={32} />,
    title: "Frontend Developer",
    company: "Lunar UI Labs",
    location: "Seattle, WA",
    benefits: "$89.2K/yr - $149.8K/yr · Medical · 401k",
  },
  {
    id: 4,
    icon: <BiBot size={32} />,
    title: "QA Engineer",
    company: "CyberVerify",
    location: "Austin, TX",
    benefits: "Starting at $40/hr",
    tag: "This is an ad",
  },
  {
    id: 5,
    icon: <BiCookie size={32} />,
    title: "Full Stack Developer",
    company: "Sweet Code LLC",
    location: "Remote",
    benefits: "$100K/yr - $135K/yr · 401k, Medical, Vision, Dental",
  },
  {
    id: 6,
    icon: <BiMeteor size={32} />,
    title: "Backend Engineer",
    company: "Meteor Logic",
    location: "New York, NY",
  },
  {
    id: 7,
    icon: <BiRocket size={32} />,
    title: "Cloud Engineer",
    company: "Rocket Cloud",
    location: "Denver, CO",
    benefits: "$110K/yr - $140K/yr · Medical, 401k, Remote Work Available",
    tag: "This is an ad",
  },
  {
    id: 8,
    icon: <BiChip size={32} />,
    title: "Embedded Systems Engineer",
    company: "NanoTech Inc.",
    location: "San Diego, CA",
    benefits: "$95K/yr - $120K/yr · 401k, Medical, Stock Options",
  },
  {
    id: 9,
    icon: <BiAtom size={32} />,
    title: "Machine Learning Engineer",
    company: "Quantum AI Labs",
    location: "Boston, MA",
    benefits: "$120K/yr - $160K/yr · Medical, Vision, Dental, 401k",
  },
]
